export type RunEntry = {
  agent: string;
  model: string;
  noise: boolean;
  diagPct: number;
  mitPct: number;
  e2ePct: number;
  ttdSeconds: number;
  ttmSeconds: number;
  tokens: string;
};

export type RankedRunEntry = RunEntry & {
  rank: number;
};

export type LeaderboardBenchmark = {
  id: string;
  label: string;
  summary: string;
  supportsNoise: boolean;
  cohortHref?: string;
  entries: RunEntry[];
};

export const runLeaderboardData: RunEntry[] = [
  {
    agent: "Stratus",
    model: "Claude Sonnet 4.6",
    noise: false,
    diagPct: 61.5,
    mitPct: 78.5,
    e2ePct: 54.8,
    ttdSeconds: 114.0,
    ttmSeconds: 771.1,
    tokens: "812K",
  },
  {
    agent: "Stratus",
    model: "Claude Sonnet 4.6",
    noise: true,
    diagPct: 51.5,
    mitPct: 61.1,
    e2ePct: 39.6,
    ttdSeconds: 170.5,
    ttmSeconds: 885.0,
    tokens: "464K",
  },
  {
    agent: "Stratus",
    model: "Kimi K2.5",
    noise: false,
    diagPct: 40.4,
    mitPct: 40.4,
    e2ePct: 27.4,
    ttdSeconds: 674.5,
    ttmSeconds: 1348.8,
    tokens: "413K",
  },
  {
    agent: "Stratus",
    model: "Kimi K2.5",
    noise: true,
    diagPct: 38.1,
    mitPct: 41.9,
    e2ePct: 26.7,
    ttdSeconds: 656.4,
    ttmSeconds: 1283.2,
    tokens: "443K",
  },
  {
    agent: "Claude Code",
    model: "Claude Sonnet 4.6",
    noise: false,
    diagPct: 72.6,
    mitPct: 75.6,
    e2ePct: 60.7,
    ttdSeconds: 292.5,
    ttmSeconds: 702.0,
    tokens: "1.47M",
  },
  {
    agent: "Claude Code",
    model: "Claude Sonnet 4.6",
    noise: true,
    diagPct: 62.6,
    mitPct: 76.3,
    e2ePct: 53.7,
    ttdSeconds: 314.0,
    ttmSeconds: 736.5,
    tokens: "1.71M",
  },
  {
    agent: "Codex",
    model: "GPT-5.4",
    noise: false,
    diagPct: 70.0,
    mitPct: 63.7,
    e2ePct: 53.3,
    ttdSeconds: 176.4,
    ttmSeconds: 376.0,
    tokens: "1.98M",
  },
  {
    agent: "Codex",
    model: "GPT-5.4",
    noise: true,
    diagPct: 59.3,
    mitPct: 61.9,
    e2ePct: 45.9,
    ttdSeconds: 218.1,
    ttmSeconds: 397.7,
    tokens: "1.88M",
  },
  // These GitHub Copilot results use the same 90-problem cohort and three
  // attempts per problem as the paper results above. Missing attempts count
  // as failures; token means use runs with recorded token usage.
  {
    agent: "GitHub Copilot",
    model: "GPT-5.5 (max)",
    noise: false,
    diagPct: 81.9,
    mitPct: 76.7,
    e2ePct: 70.0,
    ttdSeconds: 190.1,
    ttmSeconds: 541.0,
    tokens: "1.55M",
  },
  {
    agent: "GitHub Copilot",
    model: "GPT-5.6 Sol (max)",
    noise: false,
    diagPct: 83.3,
    mitPct: 83.7,
    e2ePct: 72.2,
    ttdSeconds: 243.0,
    ttmSeconds: 645.4,
    tokens: "2.45M",
  },
  {
    agent: "GitHub Copilot",
    model: "GPT-5.6 Terra (max)",
    noise: false,
    diagPct: 82.6,
    mitPct: 80.4,
    e2ePct: 70.0,
    ttdSeconds: 214.5,
    ttmSeconds: 610.8,
    tokens: "3.09M",
  },
  {
    agent: "GitHub Copilot",
    model: "Claude Opus 4.8 (medium)",
    noise: false,
    diagPct: 81.1,
    mitPct: 75.6,
    e2ePct: 69.3,
    ttdSeconds: 328.5,
    ttmSeconds: 551.7,
    tokens: "2.82M",
  },
  {
    agent: "GitHub Copilot",
    model: "Claude Sonnet 5 (medium)",
    noise: false,
    diagPct: 85.2,
    mitPct: 77.8,
    e2ePct: 70.7,
    ttdSeconds: 241.6,
    ttmSeconds: 419.5,
    tokens: "4.01M",
  },
];

// Results use all 21 SREGym-Lite faults and three attempts per fault. Missing
// attempts and timeouts count as failures; time means use runs with recorded
// values.
export const liteLeaderboardData: RunEntry[] = [
  {
    agent: "Claude Code",
    model: "Claude Opus 5",
    noise: false,
    diagPct: 92.1,
    mitPct: 82.5,
    e2ePct: 76.2,
    ttdSeconds: 210.1,
    ttmSeconds: 419.8,
    tokens: "1.64M",
  },
  {
    agent: "Claude Code",
    model: "Claude Opus 4.8",
    noise: false,
    diagPct: 66.7,
    mitPct: 63.5,
    e2ePct: 52.4,
    ttdSeconds: 324.4,
    ttmSeconds: 503.1,
    tokens: "1.66M",
  },
  {
    agent: "Claude Code",
    model: "Claude Sonnet 5",
    noise: false,
    diagPct: 63.5,
    mitPct: 69.8,
    e2ePct: 55.6,
    ttdSeconds: 271.5,
    ttmSeconds: 450.2,
    tokens: "2.95M",
  },
  {
    agent: "Codex",
    model: "GPT-5.6 Sol (max)",
    noise: false,
    diagPct: 95.2,
    mitPct: 85.7,
    e2ePct: 81.0,
    ttdSeconds: 211.0,
    ttmSeconds: 397.0,
    tokens: "1.42M",
  },
  {
    agent: "Codex",
    model: "GPT-5.6 Sol (medium)",
    noise: false,
    diagPct: 77.8,
    mitPct: 71.4,
    e2ePct: 58.7,
    ttdSeconds: 108.2,
    ttmSeconds: 270.6,
    tokens: "0.77M",
  },
  {
    agent: "Codex",
    model: "GPT-5.6 Luna (max)",
    noise: false,
    diagPct: 87.3,
    mitPct: 79.4,
    e2ePct: 68.3,
    ttdSeconds: 284.0,
    ttmSeconds: 492.9,
    tokens: "2.74M",
  },
  {
    agent: "Codex",
    model: "GPT-5.6 Terra (max)",
    noise: false,
    diagPct: 85.7,
    mitPct: 79.4,
    e2ePct: 69.8,
    ttdSeconds: 214.7,
    ttmSeconds: 415.8,
    tokens: "1.68M",
  },
];

// Retained as an internal historical record and intentionally not exposed on
// the site. These results use the previous 20-fault SREGym-Lite-0720 cohort.
export const lite0720LeaderboardData: RunEntry[] = [
  {
    agent: "Claude Code",
    model: "Claude Opus 5",
    noise: false,
    diagPct: 91.7,
    mitPct: 86.7,
    e2ePct: 80.0,
    ttdSeconds: 213.2,
    ttmSeconds: 418.6,
    tokens: "1.63M",
  },
  {
    agent: "Claude Code",
    model: "Claude Opus 4.8",
    noise: false,
    diagPct: 68.3,
    mitPct: 66.7,
    e2ePct: 55.0,
    ttdSeconds: 328.8,
    ttmSeconds: 503.8,
    tokens: "1.67M",
  },
  {
    agent: "Claude Code",
    model: "Claude Sonnet 5",
    noise: false,
    diagPct: 66.7,
    mitPct: 73.3,
    e2ePct: 58.3,
    ttdSeconds: 276.0,
    ttmSeconds: 449.5,
    tokens: "2.99M",
  },
  {
    agent: "Codex",
    model: "GPT-5.6 Sol (max)",
    noise: false,
    diagPct: 96.7,
    mitPct: 85.0,
    e2ePct: 81.7,
    ttdSeconds: 207.7,
    ttmSeconds: 390.5,
    tokens: "1.34M",
  },
  {
    agent: "Codex",
    model: "GPT-5.6 Luna (max)",
    noise: false,
    diagPct: 88.3,
    mitPct: 80.0,
    e2ePct: 68.3,
    ttdSeconds: 287.4,
    ttmSeconds: 490.6,
    tokens: "2.69M",
  },
  {
    agent: "Codex",
    model: "GPT-5.6 Terra (max)",
    noise: false,
    diagPct: 86.7,
    mitPct: 80.0,
    e2ePct: 70.0,
    ttdSeconds: 219.6,
    ttmSeconds: 416.3,
    tokens: "1.66M",
  },
  {
    agent: "GitHub Copilot",
    model: "GPT-5.6 Sol (medium)",
    noise: false,
    diagPct: 80.0,
    mitPct: 76.7,
    e2ePct: 65.0,
    ttdSeconds: 115.9,
    ttmSeconds: 424.3,
    tokens: "1.28M",
  },
  {
    agent: "GitHub Copilot",
    model: "GPT-5.6 Luna (medium)",
    noise: false,
    diagPct: 56.7,
    mitPct: 45.0,
    e2ePct: 40.0,
    ttdSeconds: 73.7,
    ttmSeconds: 263.0,
    tokens: "1.10M",
  },
  {
    agent: "GitHub Copilot",
    model: "GPT-5.6 Terra (medium)",
    noise: false,
    diagPct: 53.3,
    mitPct: 48.3,
    e2ePct: 36.7,
    ttdSeconds: 71.2,
    ttmSeconds: 355.3,
    tokens: "1.11M",
  },
  {
    agent: "OpenCode",
    model: "GLM-5.2 (max)",
    noise: false,
    diagPct: 75.0,
    mitPct: 70.0,
    e2ePct: 65.0,
    ttdSeconds: 408.2,
    ttmSeconds: 693.3,
    tokens: "33.6K",
  },
];

export const leaderboardBenchmarks: LeaderboardBenchmark[] = [
  {
    id: "sregym-lite-0904",
    label: "SREGym-Lite",
    summary: "SREGym-Lite-0904 · 21 faults",
    supportsNoise: false,
    cohortHref: "/problems/cohorts/sregym-lite",
    entries: liteLeaderboardData,
  },
  {
    id: "sregym-0508",
    label: "SREGym",
    summary: "SREGym-0508 · 90 faults",
    supportsNoise: true,
    cohortHref: "/problems/cohorts/sregym-0508",
    entries: runLeaderboardData,
  },
];
